apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox
        command: ['sh', '-c', 'until wget -qO- http://config-server:8888/actuator/health/readiness; do echo waiting for config-server; sleep 1; done;']
      containers:
      - name: eureka-server
        image: junbyoung/eureka-server:0.0.1
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8761
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8761
          initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
